USE Smart_poll;

CREATE TABLE OptionPoll
(
	Id INT PRIMARY KEY IDENTITY,
	PollId INT NOT NULL,
	TextOption NVARCHAR(300) NOT NULL,
	CONSTRAINT FK_OptionPull_To_Poll FOREIGN KEY (PollId) REFERENCES Poll (Id) ON DELETE CASCADE
)