USE Smart_poll;

CREATE TABLE OptionPull
(
	Id INT PRIMARY KEY IDENTITY,
	PollId INT NOT NULL,
	TextOption NVARCHAR(300) NOT NULL,
	CONSTRAINT FK_OptionPull_To_Pull FOREIGN KEY (PollId) REFERENCES Poll (Id) ON DELETE CASCADE
)