USE Smart_voting_release;

CREATE TABLE UsersAnswers
(
	IDAnswer INT PRIMARY KEY IDENTITY,
	OptionID INT NOT NULL,
	UserID INT NOT NULL,
	CONSTRAINT FK_UsersAnswers_To_Options FOREIGN KEY (OptionID) REFERENCES Options (OptionID) ON DELETE CASCADE,
	CONSTRAINT FK_UsersAnswers_To_Users FOREIGN KEY (UserID) REFERENCES Users (UserID) ON DELETE NO ACTION
)